version: '3.8'

services:
  db:
    image: postgis/postgis:14-3.2
    container_name: cropio_postgis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cropio_app
    command: bash -c "bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec puma -C config/puma.rb"
    volumes:
      - ".:/docker/app"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgis://${DB_USERNAME}:${DB_PASSWORD}@db:5432/cropio_test_development

volumes:
  pg_data:
