default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cropio_test_development
test:
  <<: *default
  database: cropio_test_test
production:
  <<: *default
  database: cropio_test_production
  username: cropio_test
  password: <%= ENV["CROPIO_TEST_DATABASE_PASSWORD"] %>
